//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;

namespace OpenDentBusiness.Crud{
	public class AutomationCrud {
		///<summary>Gets one Automation object from the database using the primary key.  Returns null if not found.</summary>
		public static Automation SelectOne(long automationNum){
			string command="SELECT * FROM automation "
				+"WHERE AutomationNum = "+POut.Long(automationNum);
			List<Automation> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one Automation object from the database using a query.</summary>
		public static Automation SelectOne(string command){
			if(RemotingClient.RemotingRole==RemotingRole.ClientWeb) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<Automation> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of Automation objects from the database using a query.</summary>
		public static List<Automation> SelectMany(string command){
			if(RemotingClient.RemotingRole==RemotingRole.ClientWeb) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<Automation> list=TableToList(Db.GetTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<Automation> TableToList(DataTable table){
			List<Automation> retVal=new List<Automation>();
			Automation automation;
			foreach(DataRow row in table.Rows) {
				automation=new Automation();
				automation.AutomationNum = PIn.Long  (row["AutomationNum"].ToString());
				automation.Description   = PIn.String(row["Description"].ToString());
				automation.Autotrigger   = (OpenDentBusiness.AutomationTrigger)PIn.Int(row["Autotrigger"].ToString());
				automation.ProcCodes     = PIn.String(row["ProcCodes"].ToString());
				automation.AutoAction    = (OpenDentBusiness.AutomationAction)PIn.Int(row["AutoAction"].ToString());
				automation.SheetDefNum   = PIn.Long  (row["SheetDefNum"].ToString());
				automation.CommType      = PIn.Long  (row["CommType"].ToString());
				automation.MessageContent= PIn.String(row["MessageContent"].ToString());
				retVal.Add(automation);
			}
			return retVal;
		}

		///<summary>Inserts one Automation into the database.  Returns the new priKey.</summary>
		public static long Insert(Automation automation){
			if(DataConnection.DBtype==DatabaseType.Oracle) {
				automation.AutomationNum=DbHelper.GetNextOracleKey("automation","AutomationNum");
				int loopcount=0;
				while(loopcount<100){
					try {
						return Insert(automation,true);
					}
					catch(Oracle.DataAccess.Client.OracleException ex){
						if(ex.Number==1 && ex.Message.ToLower().Contains("unique constraint") && ex.Message.ToLower().Contains("violated")){
							automation.AutomationNum++;
							loopcount++;
						}
						else{
							throw ex;
						}
					}
				}
				throw new ApplicationException("Insert failed.  Could not generate primary key.");
			}
			else {
				return Insert(automation,false);
			}
		}

		///<summary>Inserts one Automation into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(Automation automation,bool useExistingPK){
			if(!useExistingPK && PrefC.RandomKeys) {
				automation.AutomationNum=ReplicationServers.GetKey("automation","AutomationNum");
			}
			string command="INSERT INTO automation (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="AutomationNum,";
			}
			command+="Description,Autotrigger,ProcCodes,AutoAction,SheetDefNum,CommType,MessageContent) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(automation.AutomationNum)+",";
			}
			command+=
				 "'"+POut.String(automation.Description)+"',"
				+    POut.Int   ((int)automation.Autotrigger)+","
				+"'"+POut.String(automation.ProcCodes)+"',"
				+    POut.Int   ((int)automation.AutoAction)+","
				+    POut.Long  (automation.SheetDefNum)+","
				+    POut.Long  (automation.CommType)+","
				+"'"+POut.String(automation.MessageContent)+"')";
			if(useExistingPK || PrefC.RandomKeys) {
				Db.NonQ(command);
			}
			else {
				automation.AutomationNum=Db.NonQ(command,true);
			}
			return automation.AutomationNum;
		}

		///<summary>Inserts one Automation into the database.  Returns the new priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(Automation automation){
			if(DataConnection.DBtype==DatabaseType.MySql) {
				return InsertNoCache(automation,false);
			}
			else {
				if(DataConnection.DBtype==DatabaseType.Oracle) {
					automation.AutomationNum=DbHelper.GetNextOracleKey("automation","AutomationNum"); //Cacheless method
				}
				return InsertNoCache(automation,true);
			}
		}

		///<summary>Inserts one Automation into the database.  Provides option to use the existing priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(Automation automation,bool useExistingPK){
			bool isRandomKeys=Prefs.GetBoolNoCache(PrefName.RandomPrimaryKeys);
			string command="INSERT INTO automation (";
			if(!useExistingPK && isRandomKeys) {
				automation.AutomationNum=ReplicationServers.GetKeyNoCache("automation","AutomationNum");
			}
			if(isRandomKeys || useExistingPK) {
				command+="AutomationNum,";
			}
			command+="Description,Autotrigger,ProcCodes,AutoAction,SheetDefNum,CommType,MessageContent) VALUES(";
			if(isRandomKeys || useExistingPK) {
				command+=POut.Long(automation.AutomationNum)+",";
			}
			command+=
				 "'"+POut.String(automation.Description)+"',"
				+    POut.Int   ((int)automation.Autotrigger)+","
				+"'"+POut.String(automation.ProcCodes)+"',"
				+    POut.Int   ((int)automation.AutoAction)+","
				+    POut.Long  (automation.SheetDefNum)+","
				+    POut.Long  (automation.CommType)+","
				+"'"+POut.String(automation.MessageContent)+"')";
			if(useExistingPK || isRandomKeys) {
				Db.NonQ(command);
			}
			else {
				automation.AutomationNum=Db.NonQ(command,true);
			}
			return automation.AutomationNum;
		}

		///<summary>Updates one Automation in the database.</summary>
		public static void Update(Automation automation){
			string command="UPDATE automation SET "
				+"Description   = '"+POut.String(automation.Description)+"', "
				+"Autotrigger   =  "+POut.Int   ((int)automation.Autotrigger)+", "
				+"ProcCodes     = '"+POut.String(automation.ProcCodes)+"', "
				+"AutoAction    =  "+POut.Int   ((int)automation.AutoAction)+", "
				+"SheetDefNum   =  "+POut.Long  (automation.SheetDefNum)+", "
				+"CommType      =  "+POut.Long  (automation.CommType)+", "
				+"MessageContent= '"+POut.String(automation.MessageContent)+"' "
				+"WHERE AutomationNum = "+POut.Long(automation.AutomationNum);
			Db.NonQ(command);
		}

		///<summary>Updates one Automation in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.  Returns true if an update occurred.</summary>
		public static bool Update(Automation automation,Automation oldAutomation){
			string command="";
			if(automation.Description != oldAutomation.Description) {
				if(command!=""){ command+=",";}
				command+="Description = '"+POut.String(automation.Description)+"'";
			}
			if(automation.Autotrigger != oldAutomation.Autotrigger) {
				if(command!=""){ command+=",";}
				command+="Autotrigger = "+POut.Int   ((int)automation.Autotrigger)+"";
			}
			if(automation.ProcCodes != oldAutomation.ProcCodes) {
				if(command!=""){ command+=",";}
				command+="ProcCodes = '"+POut.String(automation.ProcCodes)+"'";
			}
			if(automation.AutoAction != oldAutomation.AutoAction) {
				if(command!=""){ command+=",";}
				command+="AutoAction = "+POut.Int   ((int)automation.AutoAction)+"";
			}
			if(automation.SheetDefNum != oldAutomation.SheetDefNum) {
				if(command!=""){ command+=",";}
				command+="SheetDefNum = "+POut.Long(automation.SheetDefNum)+"";
			}
			if(automation.CommType != oldAutomation.CommType) {
				if(command!=""){ command+=",";}
				command+="CommType = "+POut.Long(automation.CommType)+"";
			}
			if(automation.MessageContent != oldAutomation.MessageContent) {
				if(command!=""){ command+=",";}
				command+="MessageContent = '"+POut.String(automation.MessageContent)+"'";
			}
			if(command==""){
				return false;
			}
			command="UPDATE automation SET "+command
				+" WHERE AutomationNum = "+POut.Long(automation.AutomationNum);
			Db.NonQ(command);
			return true;
		}

		///<summary>Returns true if Update(Automation,Automation) would make changes to the database.
		///Does not make any changes to the database and can be called before remoting role is checked.</summary>
		public static bool UpdateComparison(Automation automation,Automation oldAutomation) {
			if(automation.Description != oldAutomation.Description) {
				return true;
			}
			if(automation.Autotrigger != oldAutomation.Autotrigger) {
				return true;
			}
			if(automation.ProcCodes != oldAutomation.ProcCodes) {
				return true;
			}
			if(automation.AutoAction != oldAutomation.AutoAction) {
				return true;
			}
			if(automation.SheetDefNum != oldAutomation.SheetDefNum) {
				return true;
			}
			if(automation.CommType != oldAutomation.CommType) {
				return true;
			}
			if(automation.MessageContent != oldAutomation.MessageContent) {
				return true;
			}
			return false;
		}

		///<summary>Deletes one Automation from the database.</summary>
		public static void Delete(long automationNum){
			string command="DELETE FROM automation "
				+"WHERE AutomationNum = "+POut.Long(automationNum);
			Db.NonQ(command);
		}

	}
}