//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;

namespace OpenDentBusiness.Crud{
	public class RecallCrud {
		///<summary>Gets one Recall object from the database using the primary key.  Returns null if not found.</summary>
		public static Recall SelectOne(long recallNum){
			string command="SELECT * FROM recall "
				+"WHERE RecallNum = "+POut.Long(recallNum);
			List<Recall> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one Recall object from the database using a query.</summary>
		public static Recall SelectOne(string command){
			if(RemotingClient.RemotingRole==RemotingRole.ClientWeb) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<Recall> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of Recall objects from the database using a query.</summary>
		public static List<Recall> SelectMany(string command){
			if(RemotingClient.RemotingRole==RemotingRole.ClientWeb) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<Recall> list=TableToList(Db.GetTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<Recall> TableToList(DataTable table){
			List<Recall> retVal=new List<Recall>();
			Recall recall;
			foreach(DataRow row in table.Rows) {
				recall=new Recall();
				recall.RecallNum          = PIn.Long  (row["RecallNum"].ToString());
				recall.PatNum             = PIn.Long  (row["PatNum"].ToString());
				recall.DateDueCalc        = PIn.Date  (row["DateDueCalc"].ToString());
				recall.DateDue            = PIn.Date  (row["DateDue"].ToString());
				recall.DatePrevious       = PIn.Date  (row["DatePrevious"].ToString());
				recall.RecallInterval     = new Interval(PIn.Int(row["RecallInterval"].ToString()));
				recall.RecallStatus       = PIn.Long  (row["RecallStatus"].ToString());
				recall.Note               = PIn.String(row["Note"].ToString());
				recall.IsDisabled         = PIn.Bool  (row["IsDisabled"].ToString());
				recall.DateTStamp         = PIn.DateT (row["DateTStamp"].ToString());
				recall.RecallTypeNum      = PIn.Long  (row["RecallTypeNum"].ToString());
				recall.DisableUntilBalance= PIn.Double(row["DisableUntilBalance"].ToString());
				recall.DisableUntilDate   = PIn.Date  (row["DisableUntilDate"].ToString());
				recall.DateScheduled      = PIn.Date  (row["DateScheduled"].ToString());
				retVal.Add(recall);
			}
			return retVal;
		}

		///<summary>Inserts one Recall into the database.  Returns the new priKey.</summary>
		public static long Insert(Recall recall){
			if(DataConnection.DBtype==DatabaseType.Oracle) {
				recall.RecallNum=DbHelper.GetNextOracleKey("recall","RecallNum");
				int loopcount=0;
				while(loopcount<100){
					try {
						return Insert(recall,true);
					}
					catch(Oracle.DataAccess.Client.OracleException ex){
						if(ex.Number==1 && ex.Message.ToLower().Contains("unique constraint") && ex.Message.ToLower().Contains("violated")){
							recall.RecallNum++;
							loopcount++;
						}
						else{
							throw ex;
						}
					}
				}
				throw new ApplicationException("Insert failed.  Could not generate primary key.");
			}
			else {
				return Insert(recall,false);
			}
		}

		///<summary>Inserts one Recall into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(Recall recall,bool useExistingPK){
			if(!useExistingPK && PrefC.RandomKeys) {
				recall.RecallNum=ReplicationServers.GetKey("recall","RecallNum");
			}
			string command="INSERT INTO recall (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="RecallNum,";
			}
			command+="PatNum,DateDueCalc,DateDue,DatePrevious,RecallInterval,RecallStatus,Note,IsDisabled,RecallTypeNum,DisableUntilBalance,DisableUntilDate,DateScheduled) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(recall.RecallNum)+",";
			}
			command+=
				     POut.Long  (recall.PatNum)+","
				+    POut.Date  (recall.DateDueCalc)+","
				+    POut.Date  (recall.DateDue)+","
				+    POut.Date  (recall.DatePrevious)+","
				+    POut.Int   (recall.RecallInterval.ToInt())+","
				+    POut.Long  (recall.RecallStatus)+","
				+"'"+POut.String(recall.Note)+"',"
				+    POut.Bool  (recall.IsDisabled)+","
				//DateTStamp can only be set by MySQL
				+    POut.Long  (recall.RecallTypeNum)+","
				+"'"+POut.Double(recall.DisableUntilBalance)+"',"
				+    POut.Date  (recall.DisableUntilDate)+","
				+    POut.Date  (recall.DateScheduled)+")";
			if(useExistingPK || PrefC.RandomKeys) {
				Db.NonQ(command);
			}
			else {
				recall.RecallNum=Db.NonQ(command,true);
			}
			return recall.RecallNum;
		}

		///<summary>Inserts one Recall into the database.  Returns the new priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(Recall recall){
			if(DataConnection.DBtype==DatabaseType.MySql) {
				return InsertNoCache(recall,false);
			}
			else {
				if(DataConnection.DBtype==DatabaseType.Oracle) {
					recall.RecallNum=DbHelper.GetNextOracleKey("recall","RecallNum"); //Cacheless method
				}
				return InsertNoCache(recall,true);
			}
		}

		///<summary>Inserts one Recall into the database.  Provides option to use the existing priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(Recall recall,bool useExistingPK){
			bool isRandomKeys=Prefs.GetBoolNoCache(PrefName.RandomPrimaryKeys);
			string command="INSERT INTO recall (";
			if(!useExistingPK && isRandomKeys) {
				recall.RecallNum=ReplicationServers.GetKeyNoCache("recall","RecallNum");
			}
			if(isRandomKeys || useExistingPK) {
				command+="RecallNum,";
			}
			command+="PatNum,DateDueCalc,DateDue,DatePrevious,RecallInterval,RecallStatus,Note,IsDisabled,RecallTypeNum,DisableUntilBalance,DisableUntilDate,DateScheduled) VALUES(";
			if(isRandomKeys || useExistingPK) {
				command+=POut.Long(recall.RecallNum)+",";
			}
			command+=
				     POut.Long  (recall.PatNum)+","
				+    POut.Date  (recall.DateDueCalc)+","
				+    POut.Date  (recall.DateDue)+","
				+    POut.Date  (recall.DatePrevious)+","
				+    POut.Int   (recall.RecallInterval.ToInt())+","
				+    POut.Long  (recall.RecallStatus)+","
				+"'"+POut.String(recall.Note)+"',"
				+    POut.Bool  (recall.IsDisabled)+","
				//DateTStamp can only be set by MySQL
				+    POut.Long  (recall.RecallTypeNum)+","
				+"'"+POut.Double(recall.DisableUntilBalance)+"',"
				+    POut.Date  (recall.DisableUntilDate)+","
				+    POut.Date  (recall.DateScheduled)+")";
			if(useExistingPK || isRandomKeys) {
				Db.NonQ(command);
			}
			else {
				recall.RecallNum=Db.NonQ(command,true);
			}
			return recall.RecallNum;
		}

		///<summary>Updates one Recall in the database.</summary>
		public static void Update(Recall recall){
			string command="UPDATE recall SET "
				+"PatNum             =  "+POut.Long  (recall.PatNum)+", "
				+"DateDueCalc        =  "+POut.Date  (recall.DateDueCalc)+", "
				+"DateDue            =  "+POut.Date  (recall.DateDue)+", "
				+"DatePrevious       =  "+POut.Date  (recall.DatePrevious)+", "
				+"RecallInterval     =  "+POut.Int   (recall.RecallInterval.ToInt())+", "
				+"RecallStatus       =  "+POut.Long  (recall.RecallStatus)+", "
				+"Note               = '"+POut.String(recall.Note)+"', "
				+"IsDisabled         =  "+POut.Bool  (recall.IsDisabled)+", "
				//DateTStamp can only be set by MySQL
				+"RecallTypeNum      =  "+POut.Long  (recall.RecallTypeNum)+", "
				+"DisableUntilBalance= '"+POut.Double(recall.DisableUntilBalance)+"', "
				+"DisableUntilDate   =  "+POut.Date  (recall.DisableUntilDate)+", "
				+"DateScheduled      =  "+POut.Date  (recall.DateScheduled)+" "
				+"WHERE RecallNum = "+POut.Long(recall.RecallNum);
			Db.NonQ(command);
		}

		///<summary>Updates one Recall in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.  Returns true if an update occurred.</summary>
		public static bool Update(Recall recall,Recall oldRecall){
			string command="";
			if(recall.PatNum != oldRecall.PatNum) {
				if(command!=""){ command+=",";}
				command+="PatNum = "+POut.Long(recall.PatNum)+"";
			}
			if(recall.DateDueCalc != oldRecall.DateDueCalc) {
				if(command!=""){ command+=",";}
				command+="DateDueCalc = "+POut.Date(recall.DateDueCalc)+"";
			}
			if(recall.DateDue != oldRecall.DateDue) {
				if(command!=""){ command+=",";}
				command+="DateDue = "+POut.Date(recall.DateDue)+"";
			}
			if(recall.DatePrevious != oldRecall.DatePrevious) {
				if(command!=""){ command+=",";}
				command+="DatePrevious = "+POut.Date(recall.DatePrevious)+"";
			}
			if(recall.RecallInterval != oldRecall.RecallInterval) {
				if(command!=""){ command+=",";}
				command+="RecallInterval = "+POut.Int(recall.RecallInterval.ToInt())+"";
			}
			if(recall.RecallStatus != oldRecall.RecallStatus) {
				if(command!=""){ command+=",";}
				command+="RecallStatus = "+POut.Long(recall.RecallStatus)+"";
			}
			if(recall.Note != oldRecall.Note) {
				if(command!=""){ command+=",";}
				command+="Note = '"+POut.String(recall.Note)+"'";
			}
			if(recall.IsDisabled != oldRecall.IsDisabled) {
				if(command!=""){ command+=",";}
				command+="IsDisabled = "+POut.Bool(recall.IsDisabled)+"";
			}
			//DateTStamp can only be set by MySQL
			if(recall.RecallTypeNum != oldRecall.RecallTypeNum) {
				if(command!=""){ command+=",";}
				command+="RecallTypeNum = "+POut.Long(recall.RecallTypeNum)+"";
			}
			if(recall.DisableUntilBalance != oldRecall.DisableUntilBalance) {
				if(command!=""){ command+=",";}
				command+="DisableUntilBalance = '"+POut.Double(recall.DisableUntilBalance)+"'";
			}
			if(recall.DisableUntilDate != oldRecall.DisableUntilDate) {
				if(command!=""){ command+=",";}
				command+="DisableUntilDate = "+POut.Date(recall.DisableUntilDate)+"";
			}
			if(recall.DateScheduled != oldRecall.DateScheduled) {
				if(command!=""){ command+=",";}
				command+="DateScheduled = "+POut.Date(recall.DateScheduled)+"";
			}
			if(command==""){
				return false;
			}
			command="UPDATE recall SET "+command
				+" WHERE RecallNum = "+POut.Long(recall.RecallNum);
			Db.NonQ(command);
			return true;
		}

		///<summary>Returns true if Update(Recall,Recall) would make changes to the database.
		///Does not make any changes to the database and can be called before remoting role is checked.</summary>
		public static bool UpdateComparison(Recall recall,Recall oldRecall) {
			if(recall.PatNum != oldRecall.PatNum) {
				return true;
			}
			if(recall.DateDueCalc != oldRecall.DateDueCalc) {
				return true;
			}
			if(recall.DateDue != oldRecall.DateDue) {
				return true;
			}
			if(recall.DatePrevious != oldRecall.DatePrevious) {
				return true;
			}
			if(recall.RecallInterval != oldRecall.RecallInterval) {
				return true;
			}
			if(recall.RecallStatus != oldRecall.RecallStatus) {
				return true;
			}
			if(recall.Note != oldRecall.Note) {
				return true;
			}
			if(recall.IsDisabled != oldRecall.IsDisabled) {
				return true;
			}
			//DateTStamp can only be set by MySQL
			if(recall.RecallTypeNum != oldRecall.RecallTypeNum) {
				return true;
			}
			if(recall.DisableUntilBalance != oldRecall.DisableUntilBalance) {
				return true;
			}
			if(recall.DisableUntilDate != oldRecall.DisableUntilDate) {
				return true;
			}
			if(recall.DateScheduled != oldRecall.DateScheduled) {
				return true;
			}
			return false;
		}

		///<summary>Deletes one Recall from the database.</summary>
		public static void Delete(long recallNum){
			string command="DELETE FROM recall "
				+"WHERE RecallNum = "+POut.Long(recallNum);
			Db.NonQ(command);
		}

	}
}